# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  back-end:
    image: aaren882/js_ai_model_school
    container_name: server
    environment:
      OLLAMA_HOST_URL: http://ollama:11434
      OLLAMA_MODEL: gemma3
      DB_IP: db-connect
      DB_PW: pw
      DB_PORT: 5432
      PORT: 9000
    volumes:
      - analyze-data:/var/lib/university_analyze
    depends_on:
      - ollama
      - db-connect
    ports:
      - 3000:9000 # To <- FROM
    expose:
      - 9000
  db-connect:
    image: postgres:latest
    container_name: pg
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: School_Test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5442:5432
    expose:
      - 5432
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

# Use for remote DB admin
  adminer:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nfu.edu.tw
      PGADMIN_DEFAULT_PASSWORD: pw
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    ports:
      - 5050:80

# Volumes
volumes:
  analyze-data:
  ollama-data:
  db-data:
  pgadmin-data:
  
configs:
  pgpass:
    content: db-connect:5432:*:postgres:postgres
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "Database for School",
            "Host": "db-connect",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }
# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       db-password
#     volumes:
#       db-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB=example
#       POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

